accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]   

homes/urls.py
from django.urls import path
from . import views

app_name = "homes"
urlpatterns = [
    path("", views.base, name='base'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("homes.urls")),
    path("accounts/", include("accounts.urls")),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

homes/models.py
from django.db import models

accounts/views.py
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.shortcuts import render, redirect

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']

        user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
        user.save()
        print("User created!")

        return redirect('/')

    else:
        return render(request, 'register.html')
        

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')

        else:
            messages.info(request, 'invalid user')
            return redirect('/login')

    else:
        return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

homes/views.py
from django.shortcuts import render

def base(request):
    return render(request, "base.html")

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>home</title>

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

</head>
<body>
	<nav class="navbar navbar-expand-sm" style="background-color: #3F729B;">
		<!-- Brand/Logo -->
		<a class="navbar-brand" style="color: #00ffff" href="{% url 'homes:base' %}">Cluster</a>
		<button class="navbar-toggler" type="button" data-toggler="collapse" data-target="#collapsibleNavbar">
			<span class="navbar-toggler-icon"></span>
		</button>

		<!-- Links -->
		<div class="collapse navbar-collapse" id="collapsibleNavbar">

			<!-- Search bar -->
			<form class="form-inline">
				<input class="form-control mr-sm-2" type="text" placeholder="Search">
				<button class="btn btn-success" type="submit">Search</button>
			</form>
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link text-white" href="#">About</a>
			</li>

			<li class="nav-item">
				<a class="nav-link text-white" href="#">Products</a>
			</li>

			{% if user.is_authenticated %}
				<li class="nav-item text-info" style="margin-top: 8px;">Hi, {{ user.username }}</li>
				<li class="nav-item">
					<a class="nav-link text-white" href="{% url 'accounts:logout' %}">Logout</a>
				</li>

			{% else %}
				<li class="nav-item">
					<a class="nav-link text-white" href="{% url 'accounts:register' %}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link text-white" href="{% url 'accounts:login' %}">Log in</a>
				</li>
			{% endif %}
		</ul>
		</div>
	</nav>

	<h3 class="text-secondary" style="margin-left: 100px; margin-top: 10px;">Welcome to our site</h3>	
	<p class="text-info" style="margin-left:70px">
		This is a E-commerece site
		our site will help you about e-commerce
	</p>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

	<title>login</title>
</head>
<body>
	<div class="container mt-5">
		{% for message in messages %}
	<p class="text-center text-gray">{{ message }}</p>
	{% endfor %}
	<!-- Material form login -->
	<div class="card" style="width: 50%; margin-left: 25%;">
		<h5 class="card-header bg-info text-white text-center py-4"><strong>Log in</strong></h5>

		<!-- card content -->
		<div class="card-body px-lg-5 pt-0">
			<!-- form -->
			<form action="/accounts/login/" method="post" class="text-center" style="color: #757575">
				{% csrf_token %}

				<!-- username -->
				<div class="md-form mt-3">
		      		<input type="text" class="form-control" name="username" placeholder="Username" required>
		    	</div>

		    	<!-- password -->
		    	<div class="md-form mt-3">
		      		<input type="password" class="form-control" name="password"
		      		placeholder="Password" required>
		    	</div>

		    	<div class="d-flex justify-content-around mt-3">
		    		<div>
		    			<!-- Remember me -->
		    			<div class="form-check">
		    				<input type="checkbox" class="form-check-input" id="rememberme">
		    				<label class="form-check-lable" for="rememberme">Remember me</label>
		    			</div>
		    		</div>
		    		<div>
		    			<!-- forgot password -->
		    			<a href="">Forgot password</a>
		    		</div>
		    	</div>

		    	<!-- sign in button -->
				<button type="submit" class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0">Log in</button>

				<!-- Register -->
				<p>Not a member?
					<a href="{% url 'accounts:register' %}">Register Here</a>
				</p>

				<!-- Social login -->
				<p>or sign in with</p>
				<a href="" type="button" class="btn-floating btn-fb btn-sm">
					<i class="fab fa-facebook-f"></i>
				</a>
				<a href="" type="button" class="btn-floating btn-tw btn-sm">
					<i class="fab fa-twitter"></i>
				</a>
				<a href="" type="button" class="btn-floating btn-li btn-sm">
					<i class="fab fa-linkedin-in"></i>
				</a>
				<a href="https://github.com/" type="button" class="btn-floating btn-git btn-sm">
					<i class="fab fa-github"></i>
				</a>
			</form>
		</div>
	</div>	
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

	<title>Registration</title>
  
</head>
<body>
	<div class="container mt-5">
		{% for message in messages %}
		<p class="text-center text-gray">{{ message }}</p>
		{% endfor %}

		<!-- Material form register -->
		<div class="card" style="width: 50%; margin-left: 25%;">
		<h5 class="card-header bg-info text-white text-center py-4"><strong>Register</strong></h5>

		<!-- card content -->
		<div class="card-body px-lg-5 pt-0">
			<!-- form -->
			<form action="/accounts/register/" method="post" class="text-center" style="color: #757575">
				{% csrf_token %}

				<!-- first name -->
				<div class="md-form mt-3">
					<input type="text" class="form-control" name="first_name" placeholder="First Name" required>
				</div>

				<!--  last name -->
				<div class="md-form mt-3">
					<input type="text" class="form-control" name="last_name" placeholder="Last Name">
				</div> 

				<!-- email -->
				<div class="md-form mt-3">
					<input type="email" class="form-control" name="email" placeholder="Enter Email" required>
				</div>

				<!-- username -->
				<div class="md-form mt-3">
					<input type="text" class="form-control" name="username" placeholder="Username" required>
				</div>

				<!-- password -->
				<div class="md-form mt-3">
					<input type="password" class="form-control" name="password" placeholder="Enter Password" required>
				</div>

				<!-- sign in button -->
				<button type="submit" class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0">Register</button>

				<!-- Log in -->
				<p>If already member
					<a href="{% url 'accounts:login' %}">Login</a>
				</p>

				<!-- Social login -->
				<p>or sign in with</p>
				<a href="" type="button" class="btn-floating btn-fb btn-sm">
					<i class="fab fa-facebook-f"></i>
				</a>
				<a href="" type="button" class="btn-floating btn-tw btn-sm">
					<i class="fab fa-twitter"></i>
				</a>
				<a href="" type="button" class="btn-floating btn-li btn-sm">
					<i class="fab fa-linkedin-in"></i>
				</a>
				<a href="https://github.com/" type="button" class="btn-floating btn-git btn-sm">
					<i class="fab fa-github"></i>
				</a>
			</form>
		</div>
	</div>
	</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>